"""Emit apworld/caravan_sandwitch/locations.py from the frozen tables.

Inputs
  data/locations_v1.tsv       LOCATIONS, append-only IDs (never renumber)
  data/sphere1_observed.tsv   reached itemless in a fresh playtest
  data/sphere2_observed.tsv   reached with Antenna(+Van), pre-Grapple
  data/sphere_overrides.tsv   MANUAL corrections, highest precedence

Why overrides exist: an export records when the owner *happened to pick
something up*, not when it first became *reachable*. Whenever the owner says
"X is obtainable without Y", add a row to sphere_overrides.tsv and rerun this.
An override moves the location to that sphere and removes it from any other,
so corrections survive future exports instead of being clobbered by them.

Run: python tools/gen_locations_py.py   (then tools/gentest.ps1)
"""
import csv
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def read(path):
    with open(os.path.join(ROOT, path), encoding="utf-8") as f:
        return list(csv.DictReader(f, delimiter="\t"))


def main():
    rows = read("data/locations_v1.tsv")
    by_name = {r["name"]: r["id"] for r in rows}
    valid_ids = {r["id"] for r in rows}

    spheres = {
        1: [r["id"] for r in read("data/sphere1_observed.tsv")],
        2: [r["id"] for r in read("data/sphere2_observed.tsv")],
    }

    applied, skipped = 0, []
    for o in read("data/sphere_overrides.tsv"):
        name = o["name"].strip()
        lid = by_name.get(name) or (name if name in valid_ids else None)
        if lid is None:
            skipped.append(name)
            continue
        target = int(o["sphere"])
        for s in spheres.values():           # a location lives in one sphere
            while lid in s:
                s.remove(lid)
        if target in spheres:
            spheres[target].append(lid)
        applied += 1

    out = os.path.join(ROOT, "apworld", "caravan_sandwitch", "locations.py")
    with open(out, "w", encoding="utf-8") as f:
        f.write('"""GENERATED by tools/gen_locations_py.py - do not hand-edit.\n\n')
        f.write('Location IDs are append-only; never renumber a published id.\n"""\n\n')
        f.write("LOCATIONS = [\n")
        for r in rows:
            f.write(f'    ("{r["key"]}", "{r["name"]}", {r["id"]}, '
                    f'{int(r["chapter"] or 0)}, "{r["kind"]}", "{r["category"]}"),\n')
        f.write("]\n\n")
        f.write("# Reachable with NO items (empirical Sphere 1).\n")
        f.write("SPHERE1_IDS = frozenset([\n")
        for i in spheres[1]:
            f.write(f"    {i},\n")
        f.write("])\n\n")
        f.write("# Reachable with Antenna (+Van), pre-Grapple (empirical Sphere 2).\n")
        f.write("SPHERE2_IDS = frozenset([\n")
        for i in spheres[2]:
            f.write(f"    {i},\n")
        f.write("])\n")

    print(f"locations.py: {len(rows)} locations, "
          f"S1={len(spheres[1])}, S2={len(spheres[2])}, "
          f"{applied} override(s) applied")
    if skipped:
        print("  WARNING: override names not found in locations_v1.tsv:")
        for n in skipped:
            print(f"    {n}")


if __name__ == "__main__":
    main()
